### ISSUE TITLE
Not published for 2.12

### ISSUE THREAD

**Issue by ghost** [Spinoco/fs2-zk#2]
The build is setup to produce 2.12 artifacts as part of a cross build and publishLocal works. The 0.1.5 artifact is only published as 2.11  though. It would be great if I didn't have to build and publish the 0.1.5 artifacts for 2.12 locally.

**Comment by pchlupacek** [comment]
@chris-vale-ck thanks for pointing this out. We will be releasing new version of fs2-zk once the 0.9.7 fs2 will be available. I'll make sure that all artificats will be published for both scala versions.

**Comment by ghost** [comment]
Appreciate the update! thanks a lot

**Comment by pchlupacek** [comment]
@chris-vale-ck As of 0.1.6 fs2-zk is published for 2.12 as well.
